# Generated by Django 3.0.8 on 2020-10-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolment',
            old_name='Level',
            new_name='Year',
        ),
    ]
