# Generated by Django 3.0.8 on 2020-10-21 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibas', '0002_auto_20201021_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PhoneNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(9)]),
        ),
    ]
