# Generated by Django 3.0.8 on 2020-11-05 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibas', '0003_auto_20201021_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='PhoneNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='PhoneNumber',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
