# Generated by Django 3.0.8 on 2020-11-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibas', '0004_auto_20201105_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='ProgrammeName',
            field=models.TextField(max_length=40),
        ),
    ]
