# Generated by Django 3.0.8 on 2020-11-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibas', '0007_auto_20201105_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='ActionTaken',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='IssueDescription',
            field=models.TextField(max_length=100),
        ),
    ]
